name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    concurrency:
      group: "deploy-${{ github.ref_name }}-${{ github.event.pull_request.number }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - run: corepack prepare --activate

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: pnpm cdk deploy --require-approval=never
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
